### ISSUE TITLE
Latest tag broken

### ISSUE THREAD

**Issue by johntmyers** [mvertes/docker-alpine-mongo#10]
The latest push to Dockerhub is broken.

```
Error relocating /usr/bin/mongod: _ZNK5boost16re_detail_10600031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_: symbol not found
Error relocating /usr/bin/mongod: _ZNK5boost16re_detail_10600031cpp_regex_traits_implementationIcE9transformEPKcS4_: symbol not found
```

**Comment by w32blaster** [comment]
yep, I also have the same issue.

**Comment by aPoCoMiLogin** [comment]
Same issue here with latest.

**Comment by mvertes** [comment]
There are several problems. The one mentioned above needs to be investigated.  But The mongodb package in alpine-linux needs also to be reverted to version 3.2.4 instead of 3.2.7 which breaks the mongo shell (see https://bugs.alpinelinux.org/issues/6187). So I will file a patch to revert to 3.2.4, waiting for resolution of problems which are outside the scope of mongodb itself.

I contributed for some months the set of patches to port a recent mongodb on alpinelinux  and did not upgrade to 3.2.7 for this reason, but somebody else did (and without testing), thus those problems. So I will try to clarify this with the alpine-linux team.

The last thing which bothers me is the lack of control in the docker hub automated builds. The previous build was perfectly ok, and I could not find a way to way to recover it. I may disable automated build temporarily and provide a static build if that helps.

**Comment by aPoCoMiLogin** [comment]
@mvertes you can pull previous build by digests, tag it locally as latest and then push it. There is a way to pin image to exact build it's digests: https://docs.docker.com/engine/reference/commandline/pull/

for example:

```
$ docker pull mvertes/alpine-mongo@sha256:c5ac43375ad7cc4b2a490660463debaf9967b676e9e4671729b921ff23e33e34
sha256:c5ac43375ad7cc4b2a490660463debaf9967b676e9e4671729b921ff23e33e34: Pulling from mvertes/alpine-mongo

6d6a6a7dae29: Already exists 
973d100c117e: Pull complete 
09915e289c50: Pull complete 
5547d3a84cb0: Pull complete 
Digest: sha256:c5ac43375ad7cc4b2a490660463debaf9967b676e9e4671729b921ff23e33e34
Status: Downloaded newer image for mvertes/alpine-mongo@sha256:c5ac43375ad7cc4b2a490660463debaf9967b676e9e4671729b921ff23e33e34
```

find image ID:

```
$ docker images --digests
REPOSITORY                  TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
mvertes/alpine-mongo        <none>              sha256:c5ac43375ad7cc4b2a490660463debaf9967b676e9e4671729b921ff23e33e34   7f179837fed9        5 months ago        136.5 MB
mvertes/alpine-mongo        3.2.4-1             <none>                                                                    365390326258        6 months ago        136.5 MB
```

tag it as latest:

```
$ docker tag 7f179837fed9 mvertes/alpine-mongo:latest
```

push it:

```
$ docker push mvertes/alpine-mongo:latest
```

**Comment by mvertes** [comment]
Very useful, thanks

**Comment by ilgarm** [comment]
have this problem as well

**Comment by sallespro** [comment]
Hi, Just follow https://github.com/aPoCoMiLogin recopy and it’s done for now.

Em 18/10/2016, à(s) 20:45, Ilgar Mashayev <notifications@github.com> escreveu:

**Comment by ilgarm** [comment]
@sallespro thanks for the hint, but I meant broken mongodb package in alpine repository. I should have been more specific. I am not using pre-built docker image.

**Comment by mvertes** [comment]
It should be all good now with the latest tag based on mongodb-3.2.10. I also reduced the image size which is 78 MB (30 MB compressed) vs 136 MB (54 MB compressed).

**Comment by ilgarm** [comment]
@mvertes, I installed 3.2.10 recently, it did not declare libcrypto1.0 as a dependency, I think. So I had to install it manually. Normally, declared dependencies installed by the package manager. But at least, it is functional. Thank you!
