### ISSUE TITLE
Share port to real OS

### ISSUE THREAD

**Issue by DrMartiner** [mvertes/docker-alpine-mongo#20]
Hello everyone

How can I forward mongo port (27017) to a real OS to localhost? 

I try to do this, but I had not succeed:
```python
  mongo:
    image: 'mongo:latest'
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
# ......
```

**Comment by halfer** [comment]
If this is a Docker Compose YAML file, then the `- 27017:27017` line should be sufficient. I tend to enclose mine in quotes, but I presume it is not necessary.

I would say the issues list for this container is not the best place for general Docker Compose questions. Would you ask this on Stack Overflow or somewhere similar? You may need to add more detail though, since what you have here should work.

Note also that the image you are referring to is not `mvertes/alpine-mongo` - presumably `mongo` is the one from the official Mongo project?

**Comment by mvertes** [comment]
The question is not related to this docker image
